//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>API Rest to expose the methods of the entity [Audit]</summary>
using Microsoft.AspNetCore.Mvc;

namespace SoftwareOne.BaseLine.Api.Controllers
{
    /// <summary>
    /// API RestFull to expose the methods of the entity [Audit]
    /// </summary>
    [ApiVersion(Common.Constant.VersionApiv1)]
    public partial class AuditController :
                          Core.Controller.BaseController<Entities.Audit,
                                         EntitiesDto.Audit,
                                         Interfaces.ApplicationServices.Facade.IAudit>
    {
        /// <summary>
        /// Post method not implemented for the entity [Audit].
        /// </summary>
        /// <param name="objCreate"></param>
        /// <returns></returns>
        [HttpPost]
        public override Task<IActionResult> Post([FromBody] EntitiesDto.Audit objCreate)
        {
            return Task.FromResult<IActionResult>(NotFound());
        }

        /// <summary>
        /// Put method not implemented for the entity [Audit].
        /// </summary>
        /// <param name="objUpdate"></param>
        /// <returns></returns>
        [HttpPut]
        public override Task<IActionResult> Put([FromBody] EntitiesDto.Audit objUpdate)
        {
            return Task.FromResult<IActionResult>(NotFound());
        }

        /// <summary>
        /// Delete method not implemented for the entity [Audit].
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpDelete("{id:int}")]
        public override Task<IActionResult> Delete(int id)
        {
            return Task.FromResult<IActionResult>(NotFound());
        }
    }
}