//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Application Settings Enumerations</summary>
namespace SoftwareOne.BaseLine.Core.Enumerations
{
    /// <summary>
    /// Application Settings Enumerations
    /// </summary>
    public class SwoEnumApplication
    {
        /// <summary>
        /// Enumeration of Ordering Items
        /// </summary>
        public enum Orden
        {
            Asc,
            Desc
        }

        /// <summary>
        /// Enumeration to represent the Operations that will be executed in the Dynamic Expressions.
        /// </summary>
        public enum OperationExpression
        {
            Equals,
            NotEquals,
            Minor,
            MinorEquals,
            Mayor,
            MayorEquals,
            Like,
            NotLike,
            StartsWith,
            NotStartsWith,
            EndsWith,
            NotEndsWith,
            Contains,
            Any
        }

        /// <summary>
        /// Enumeration to represent the Conditionals that will be executed in the Dynamic Expressions.
        /// </summary>
        public enum ConditionalExpression
        {
            And,
            Or
        }

        /// <summary>
        /// 
        /// </summary>
        public enum TypeError { }

        public enum TypeAudit
        {
            Create,
            Update,
            Delete,
            Get, // Not Implemented
            List // Not Implemented
        }
    }
}