//------------------------------------------------------------------------------
// <auto-generated>
//     This code is part of the framework base.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class with extended methods to centralize specific functionalities of each type of object.</summary>
namespace SoftwareOne.BaseLine.Core.ExtensionMethods
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Globalization;
    using System.Linq.Expressions;
    using System.Reflection;
    using System.Text;
    using System.Text.Json;
    using SoftwareOne.BaseLine.Core.RequestDto;
    using static SoftwareOne.BaseLine.Core.Enumerations.SwoEnumApplication;
    using SoftwareOne.BaseLine.Core.ExpressionHelper;

    /// <summary>
    /// Class with extended methods to centralize specific functionalities of each type of object.
    /// </summary>
    public static partial class ExtensionMethods
    {
        /// <summary>
        /// It is responsible for comparing two objects.
        /// </summary>
        /// <typeparam name="T">Generic type for an object.</typeparam>
        /// <param name="objectFromCompare">The object to compare.</param>
        /// <param name="objectToCompare">Object to which it is compared.</param>
        /// <returns>Message with the result of the comparison.</returns>
        public static string CompareEquals<T>(this T objectFromCompare, T objectToCompare)
            where T : class
        {
            string messageCompareEquals = ValidateCompareEquals(objectFromCompare, objectToCompare);

            if (string.IsNullOrEmpty(messageCompareEquals))
            {
                messageCompareEquals = GeFormatMessageAudit(objectFromCompare, objectToCompare);
            }

            return messageCompareEquals;
        }

        /// <summary>
        /// It is in charge of establishing the message of the audit format of the difference of the objects.
        /// </summary>
        /// <typeparam name="T">Generic type for an object.</typeparam>
        /// <param name="objectFromCompare">The object to compare.</param>
        /// <param name="objectToCompare">OObject to which it is compared.</param>
        /// <returns>Audit format message.</returns>
        private static string GeFormatMessageAudit<T>(T objectFromCompare, T objectToCompare) where T : class
        {
            const string formatMessageAudit = "<b>{0}</b>, Current value: {1}, Old value: {2}";

            StringBuilder stringComparation = new StringBuilder();
            PropertyInfo[] properties = GetProperties<T>();
            string dataFromCompare;
            string dataToCompare;

            foreach (PropertyInfo property in properties)
            {
                dataFromCompare = Convert.ToString(property.GetValue(objectFromCompare, null) ?? "", CultureInfo.InvariantCulture);
                dataToCompare = Convert.ToString(property.GetValue(objectToCompare, null) ?? "", CultureInfo.InvariantCulture);

                if (dataFromCompare != dataToCompare)
                {
                    if (stringComparation.Length > 0)
                    {
                        stringComparation.Append("<br>");
                    }

                    stringComparation.Append(string.Format(CultureInfo.InvariantCulture, formatMessageAudit, property.Name, dataFromCompare, dataToCompare));
                }
            }

            return stringComparation.ToString();
        }

        /// <summary>
        /// It is responsible for obtaining the properties of a class.
        /// </summary>
        /// <typeparam name="T">Generic type for an object.</typeparam>
        /// <returns>Properties.</returns>
        private static PropertyInfo[] GetProperties<T>() where T : class
        {
            return typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.GetProperty);
        }

        /// <summary>
        /// It is in charge of validating the objects to be compared.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="objectFromCompare">The object that you want to compare.</param>
        /// <param name="objectToCompare">The object to compare to.</param>
        /// <returns>Validation message.</returns>
        public static string ValidateCompareEquals<T>(T objectFromCompare, T objectToCompare) where T : class
        {
            string messageValidateCompareEquals = string.Empty;

            if (objectFromCompare == null && objectToCompare == null)
            {
                messageValidateCompareEquals = "Registro nuevo y antiguo vacío";
            }
            else if (objectFromCompare == null)
            {
                messageValidateCompareEquals = "Registro nuevo vacío";
            }
            else if (objectToCompare == null)
            {
                messageValidateCompareEquals = "Registro antiguo vacío";
            }

            return messageValidateCompareEquals;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="valid"></param>
        /// <returns></returns>
        public static bool IsNull<T>([ValidatedNotNull] this T valid) where T : class => valid == null;

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="query"></param>
        /// <param name="orderByMember"></param>
        /// <param name="direction"></param>
        /// <returns></returns>
        public static IQueryable<T> OrderByDynamic<T>(this IQueryable<T> query,
                                                      string orderByMember,
                                                      Orden direction)
        {
            var OrderBy = ExpressionHelper.OrderBy(query, orderByMember, direction);
            if (OrderBy.IsNotNull())
            {
                return query.Provider.CreateQuery<T>(OrderBy);
            }

            return query;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="query"></param>
        /// <param name="orderByMember"></param>
        /// <param name="direction"></param>
        /// <returns></returns>
        public static IQueryable<T> OrderByDynamic<T>(this IQueryable<T> query,
                                                      Filter orderByMember)
        {
            if (orderByMember.Sorts.IsNotNull())
            {
                MethodCallExpression OrderBy;
                for (int i = 0; i < orderByMember.Sorts.Count; i++)
                {
                    if (!Enum.TryParse(orderByMember.Sorts[i].Direction.FirstCharToUpper(), out Orden eOrden))
                    {
                        eOrden = Orden.Asc;
                    }

                    OrderBy = (i == 0) ?
                                ExpressionHelper.OrderBy(query, orderByMember.Sorts[i].Name, eOrden) :
                                ExpressionHelper.ThenBy(query, orderByMember.Sorts[i].Name, eOrden);

                    if (OrderBy.IsNotNull())
                    {
                        query = query.Provider.CreateQuery<T>(OrderBy);
                    }
                }
            }

            return query;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="query"></param>
        /// <param name="whereMember"></param>
        /// <returns></returns>
        public static IQueryable<T> WhereDynamic<T>(this IQueryable<T> query,
                                                    Filter whereMember)
        {
            if (whereMember.Filters.IsNotNull())
            {
                return CreateWhereDynamic(query, whereMember);
            }

            return query;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="query"></param>
        /// <param name="whereMember"></param>
        /// <returns></returns>
        private static IQueryable<T> CreateWhereDynamic<T>(this IQueryable<T> query,
                                                           Filter whereMember)
        {
            Expression<Func<T, bool>> queryFilter = null;
            foreach (var itemWhere in whereMember.Filters)
            {
                if (itemWhere.Name.IsValid() &&
                    itemWhere.Values.IsNotNull() &&
                    itemWhere.Values.First().ToString().IsValid())
                {
                    queryFilter = AddConditionalQuery(queryFilter, itemWhere);

                    for (int i = 1; i < itemWhere.Values.Length; i++)
                    {
                        if (itemWhere.Values[i].ToString().IsValid())
                        {
                            queryFilter = queryFilter.Or(ExpressionHelper.GetCriteriaWhere<T>(itemWhere.Name,
                                                                                              itemWhere.Operator,
                                                                                              itemWhere.Values[i].ToString().Trim()));
                        }
                    }
                }
            }
            query = query.Where(queryFilter);

            return query;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="queryFilter"></param>
        /// <param name="itemWhere"></param>
        /// <returns></returns>
        private static Expression<Func<T, bool>> AddConditionalQuery<T>(Expression<Func<T, bool>> queryFilter,
                                                           ItemsFilters itemWhere)
        {
            if (queryFilter.IsNotNull())
            {
                if (itemWhere.Conditional == Enumerations.SwoEnumApplication.ConditionalExpression.Or)
                {
                    queryFilter = queryFilter.Or(ExpressionHelper.GetCriteriaWhere<T>(itemWhere.Name,
                                                                       itemWhere.Operator,
                                                                       itemWhere.Values.First().ToString().Trim()));

                }
                else
                {
                    queryFilter = queryFilter.And(ExpressionHelper.GetCriteriaWhere<T>(itemWhere.Name,
                                                                       itemWhere.Operator,
                                                                       itemWhere.Values.First().ToString().Trim()));
                }
            }
            else
            {
                queryFilter = ExpressionHelper.GetCriteriaWhere<T>(itemWhere.Name,
                                                                      itemWhere.Operator,
                                                                      itemWhere.Values.First().ToString().Trim());
            }

            return queryFilter;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="lstValid"></param>
        /// <returns></returns>
        public static bool IsNotNull<T>([ValidatedNotNull] this Collection<T> lstValid) => (lstValid != null && lstValid.Count > 0);

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="lstValid"></param>
        /// <returns></returns>
        public static bool IsNotNull<T>([ValidatedNotNull] this ICollection<T> lstValid) => (lstValid != null && lstValid.Count > 0);

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="valid"></param>
        /// <returns></returns>
        public static bool IsNotNull<T>([ValidatedNotNull] this T[] valid) => (valid != null && valid.Length > 0);

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="valid"></param>
        /// <returns></returns>
        public static bool IsNotNull<T>([ValidatedNotNull] this T valid) where T : class => valid != null;

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="valid"></param>
        /// <returns></returns>
        public static bool IsNotNull<T>([ValidatedNotNull] this IEnumerable<T> valid) where T : class => (valid != null && valid.Any());

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="lstValid"></param>
        /// <returns></returns>
        public static bool IsNotNull<T>([ValidatedNotNull] this List<T> lstValid) => (lstValid != null && lstValid.Any());

        /// <summary>
        /// Serializar Objeto
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="objJsonConvert"></param>
        /// <returns></returns>
        public static string ToJsonSerialize<T>(this T objJsonConvert) => JsonSerializer.Serialize(objJsonConvert, new JsonSerializerOptions
        {
            IgnoreNullValues = true,
            PropertyNameCaseInsensitive = true
        });

        /// <summary>
        /// Serializar Objeto
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="objJsonConvert"></param>
        /// <returns></returns>
        public static string ToJsonSerialize<T>(this T objJsonConvert, JsonSerializerOptions jsonOptions) => JsonSerializer.Serialize(objJsonConvert, jsonOptions);

        /// <summary>
        /// Deserializar Objeto
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="objJsonConvert"></param>
        /// <returns></returns>
        public static T ToJsonDeserialize<T>(this string objJsonConvert)
             where T : class, new() => JsonSerializer.Deserialize<T>(objJsonConvert);

        /// <summary>
        /// Serializar Objeto
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="objJsonConvert"></param>
        /// <returns></returns>
        public static T ToJsonDeserialize<T>(this string objJsonConvert, JsonSerializerOptions jsonOptions) => JsonSerializer.Deserialize<T>(objJsonConvert, jsonOptions);
    }
}