//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Implementation class for the facade of the application services for the Entity (AuthorizationPermissions)</summary>
using AutoMapper;

namespace SoftwareOne.BaseLine.ApplicationServices.Facade
{
    /// <summary>
    /// Implementation class for the facade of the application services for the Entity (AuthorizationPermissions)
    /// </summary>
    public partial class AuthorizationPermissions :
        Core.Facade.BaseApplicationFacade<Entities.AuthorizationPermissions,
                                     EntitiesDto.AuthorizationPermissions,
                                     Interfaces.ApplicationServices.Services.IAuthorizationPermissions>,
        Interfaces.ApplicationServices.Facade.IAuthorizationPermissions
    {
        /// <summary>
        /// Constructor to initialize the application services layer, Context Instance [AuthorizationPermissions].
        /// </summary>
        /// <param name="applicationServices">Context instance for application services</param>
        public AuthorizationPermissions(Interfaces.ApplicationServices.Services.IAuthorizationPermissions applicationServices) : base(applicationServices) {
             _mapper = new Mapper(configMapperFacade);
        }
    }
}