//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Implementation class for the facade of the application services for the Entity (Entity)</summary>
namespace SoftwareOne.BaseLine.ApplicationServices.Facade
{
    /// <summary>
    /// Implementation class for the facade of the application services for the Entity (Entity)
    /// </summary>
    public partial class Entity :
        Core.Facade.BaseApplicationFacade<Entities.Entity,
                                     EntitiesDto.Entity,
                                     Interfaces.ApplicationServices.Services.IEntity>,
        Interfaces.ApplicationServices.Facade.IEntity
    {
        /// <summary>
        /// Constructor to initialize the application services layer, Context Instance [Entity].
        /// </summary>
        /// <param name="applicationServices">Context instance for application services</param>
        public Entity(Interfaces.ApplicationServices.Services.IEntity applicationServices) : base(applicationServices) { }
    }
}