//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>API RestFull to expose the methods of the entity [Menu]</summary>
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SoftwareOne.BaseLine.Api.Controllers
{
    /// <summary>
    /// API RestFull to expose the methods of the entity [Menu]
    /// </summary>
    [ApiVersion(Common.Constant.VersionApiv1)]
    public partial class MenuController :
                          Core.Controller.BaseController<Entities.Menu,
                                         EntitiesDto.Menu,
                                         Interfaces.ApplicationServices.Facade.IMenu>
    {
        /// <summary>
        /// Method to obtain the Menu by the Role Id.
        /// </summary>
        /// <param name="request"></param>
        /// <returns>List<EntitiesDto.Menu></returns>
        [AllowAnonymous]
        [HttpGet("Role/{RoleId:int}")]
        public List<EntitiesDto.Menu> MenuByRol(int RoleId)
        {
            return this.facadeEntity.GetMenuByRole(RoleId);
        }
    }
}