//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Configuration for entity (Audit)</summary>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SoftwareOne.BaseLine.DataAccess.SqlServer.Common.Configurations
{
    public class AuditConfiguration : IEntityTypeConfiguration<Entities.Audit>
    {
        public void Configure(EntityTypeBuilder<Entities.Audit> builder)
        {
            if (builder != null) {
                builder.ToTable(nameof(Entities.Audit));
                
                builder.Property(e => e.Entity)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                builder.Property(e => e.Operation)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                builder.Property(e => e.NewRecord)
                    .HasMaxLength(500)
                    .IsUnicode(false);
                builder.Property(e => e.OldRecord)
                    .HasMaxLength(500)
                    .IsUnicode(false);
                builder.Property(e => e.UrlSource)
                    .HasMaxLength(100)
                    .IsUnicode(false);
                builder.Property(e => e.Username)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                builder.Property(e => e.IpAddress)
                    .HasMaxLength(20)
                    .IsUnicode(false);
                builder.Property(e => e.Application)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                builder.Property(e => e.AuditDate)
                    .IsUnicode(false);
            }
        }
    }
}
