//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Validator implementation for the Entity (Entity)</summary>
using FluentValidation;
using SoftwareOne.BaseLine.ApplicationTexts;
using SoftwareOne.BaseLine.Core.Validator;

namespace Base.Application.Validators
{
    public class Entity : SwoValidator<SoftwareOne.BaseLine.Entities.Entity>
    {
        /// <summary>
        /// Constant that contains max length for the name field.
        /// </summary>
        private const int NAME_MAX_LENGTH = 256;

        /// <summary>
        /// Initializes a new instance of the <see cref="Entity"/> class.
        /// </summary>
        public Entity()
        {
            // Name is mandatory
            RuleFor(entity => entity.Name)
                .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty)
                .Length(1, NAME_MAX_LENGTH).WithMessage(ResourceValidations.InvalidLength);
        }
    }
}