//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Validator implementation for the Entity (ShippingAddress)</summary>
using FluentValidation;
using SoftwareOne.BaseLine.ApplicationTexts;
using SoftwareOne.BaseLine.Core.Validator;

namespace Base.Application.Validators
{
    public class ShippingAddress : SwoValidator<SoftwareOne.BaseLine.Entities.ShippingAddress>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingAddress"/> class.
        /// </summary>
        public ShippingAddress()
        {
            // Name is mandatory
                 RuleFor(entity => entity.Name)
                    .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                    .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty);
            // Name has lenght validation
                 RuleFor(entity => entity.Name)
                    .Length(0, 50).WithMessage(ResourceValidations.InvalidLength);
            // Address is mandatory
                 RuleFor(entity => entity.Address)
                    .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                    .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty);
            // Address has lenght validation
                 RuleFor(entity => entity.Address)
                    .Length(0, 100).WithMessage(ResourceValidations.InvalidLength);
            // CustomerId is mandatory
                 RuleFor(entity => entity.CustomerId)
                    .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                    .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty);
            
            
            
            // CityId is mandatory
                 RuleFor(entity => entity.CityId)
                    .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                    .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty);
            
            
            
            

        }
    }
}