//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Validator implementation for the Entity (User)</summary>
using FluentValidation;
using SoftwareOne.BaseLine.ApplicationTexts;
using SoftwareOne.BaseLine.Core.Validator;

namespace Base.Application.Validators
{
    public class User : SwoValidator<SoftwareOne.BaseLine.Entities.User>
    {
        /// <summary>
        /// Constant that contains max length for the fields generic.
        /// </summary>
        private const int GENERIC_MAX_LENGTH = 256;

        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        public User()
        {
            // UserName length 256 
            RuleFor(entity => entity.UserName)
                .Length(0, GENERIC_MAX_LENGTH).WithMessage(ResourceValidations.InvalidLength);
            // Fullname length 256
            RuleFor(entity => entity.FullName)
                .Length(0, GENERIC_MAX_LENGTH).WithMessage(ResourceValidations.InvalidLength);
            // Email is mandatory
            RuleFor(entity => entity.Email)
                .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty)
                .Length(0, GENERIC_MAX_LENGTH).WithMessage(ResourceValidations.InvalidLength);
            // PasswordHash is mandatory
            RuleFor(entity => entity.PasswordHash)
                .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty);
            // RoleId is mandatory
            RuleFor(entity => entity.RoleId)
                .NotNull().WithMessage(ResourceValidations.FieldCantBeNull)
                .NotEmpty().WithMessage(ResourceValidations.FieldCantBeEmpty);
        }
    }
}