//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Implementation class for the facade of the application services for the Entity (AuthorizationPermissions)</summary>
using AutoMapper;

namespace SoftwareOne.BaseLine.ApplicationServices.Facade
{
    /// <summary>
    /// Implementation class for the extended facade of the application services for the Entity (AuthorizationPermissions)
    /// </summary>
    public partial class AuthorizationPermissions
    {
        protected new readonly MapperConfiguration configMapperFacade =
            new(cfg =>
            {
                cfg.CreateMap<SoftwareOne.BaseLine.Entities.AuthorizationPermissions, SoftwareOne.BaseLine.EntitiesDto.AuthorizationPermissions>();
                cfg.CreateMap<SoftwareOne.BaseLine.EntitiesDto.AuthorizationPermissions, SoftwareOne.BaseLine.Entities.AuthorizationPermissions>();
                cfg.CreateMap<SoftwareOne.BaseLine.Entities.Entity, SoftwareOne.BaseLine.EntitiesDto.Entity>();
                cfg.CreateMap<SoftwareOne.BaseLine.EntitiesDto.Entity, SoftwareOne.BaseLine.Entities.Entity>();
                cfg.CreateMap<SoftwareOne.BaseLine.Entities.Role, SoftwareOne.BaseLine.EntitiesDto.Role>();
                cfg.CreateMap<SoftwareOne.BaseLine.EntitiesDto.Role, SoftwareOne.BaseLine.Entities.Role>();
            });
    }
}