//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>This Interface represents the Facade Implementations for the application services for the Entity (Audit)</summary>
namespace SoftwareOne.BaseLine.Interfaces.ApplicationServices.Facade
{
    /// <summary>
    /// This Interface represents the Facade Implementations for the application services for the Entity(Audit)
    /// </summary>
    public partial interface IAudit : Core.Facade.IBaseApplicationFacade<Entities.Audit, EntitiesDto.Audit> { }
}