//------------------------------------------------------------------------------
// <auto-generated>
//     This code is part of the framework base.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class that represents the object with the pagination values to return the api.</summary>
namespace SoftwareOne.BaseLine.Core.RequestDto
{
    /// <summary>
    /// Class that represents the object with the pagination values to return the API.
    /// </summary>
    public class PagedList
    {
        /// <summary>
        /// Current page number.
        /// </summary>
        public int Page { get; set; }

        /// <summary>
        /// Number of Page Size
        /// </summary>
        public int PageSize { get; set; }

        /// <summary>
        /// Total Number of Pages
        /// </summary>
        public long TotalPages { get; set; }

        /// <summary>
        /// Total records
        /// </summary>
        public long MaxCount { get; set; }

        /// <summary>
        /// Number of Records From
        /// </summary>
        public long RecordsFrom { get; set; }

        /// <summary>
        /// Number of Records To
        /// </summary>
        public long RecordsTo { get; set; }
    }
}