//------------------------------------------------------------------------------
// <auto-generated>
//     This code is part of the framework base.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class that represents the object to parameterize the listings of the api.</summary>
namespace SoftwareOne.BaseLine.Core.RequestDto
{
    /// <summary>
    /// Class that represents the object to parameterize the listings of the api.
    /// </summary>
    public class ParameterGetList
    {
        /// <summary>
        /// Page Initialization
        /// </summary>
        private const int initPage = 1;

        /// <summary>
        /// Page number
        /// </summary>
        public int Page { get; set; } = initPage;

        /// <summary>
        /// Number of Records Per Page to Show
        /// </summary>
        public int NumberRecords { get; set; } = 10;

        /// <summary>
        /// Column to sort by
        /// </summary>
        public string OrderBy { get; set; }

        /// <summary>
        /// Sorting direction (Asc, Desc)
        /// </summary>
        public string DirecOrder { get; set; }
    }
}