//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>General Constants class.</summary>
namespace SoftwareOne.BaseLine.Common
{
    public static class Constant
    {
        /// <summary>
        /// Project API version 1.
        /// </summary>
        public const string VersionApiv1 = "1";

        /// <summary>
        /// The name of the Authorization header.
        /// </summary>
        public const string AUTH_HEADER = "Authorization";
    }
}