//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Implementation class for the facade of the application services for the Entity (Category)</summary>
using AutoMapper;

namespace SoftwareOne.BaseLine.ApplicationServices.Facade
{
    /// <summary>
    /// Implementation class for the extended facade of the application services for the Entity (Category)
    /// </summary>
    public partial class Category
    {
        protected new readonly MapperConfiguration configMapperFacade =
            new(cfg =>
            {
                cfg.CreateMap<SoftwareOne.BaseLine.Entities.Category, SoftwareOne.BaseLine.EntitiesDto.Category>();
                cfg.CreateMap<SoftwareOne.BaseLine.EntitiesDto.Category, SoftwareOne.BaseLine.Entities.Category>();
                cfg.CreateMap<SoftwareOne.BaseLine.Entities.Product, SoftwareOne.BaseLine.EntitiesDto.Product>();
                cfg.CreateMap<SoftwareOne.BaseLine.EntitiesDto.Product, SoftwareOne.BaseLine.Entities.Product>();

            });
    }
}