//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Implementation class for the facade of the application services for the Entity (User)</summary>
using AutoMapper;

namespace SoftwareOne.BaseLine.ApplicationServices.Facade
{
    /// <summary>
    /// Implementation class for the extended facade of the application services for the Entity (User)
    /// </summary>
    public partial class User
    {
        protected new readonly MapperConfiguration configMapperFacade =
            new(cfg =>
            {
                cfg.CreateMap<SoftwareOne.BaseLine.Entities.User, SoftwareOne.BaseLine.EntitiesDto.User>()
                    .ForMember(dest => dest.PasswordHash, act => act.Ignore());
                cfg.CreateMap<SoftwareOne.BaseLine.EntitiesDto.User, SoftwareOne.BaseLine.Entities.User>();
            });
    }
}