//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>This Interface represents the Implementations of the application services for the Entity (ShippingAddress)</summary>
namespace SoftwareOne.BaseLine.Interfaces.ApplicationServices.Services
{
    /// <summary>
    /// This Interface represents the Implementations of the application services for the Entity (ShippingAddress)
    /// </summary>
    public partial interface IShippingAddress : Core.DataAccess.IBaseRepositoryDataAccess<Entities.ShippingAddress> { }
}