//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class of the implementation of the services of the application for the Entity (Category)</summary>
namespace SoftwareOne.BaseLine.ApplicationServices.Services
{
    /// <summary>
    /// Class of the implementation of the services of the application for the Entity (Category)
    /// </summary>
    public partial class Category :
        Core.Services.BaseApplicationServices<Entities.Category,
                                              Interfaces.DataAccess.ICategory,
                                              Base.Application.Validators.Category>,
        Interfaces.ApplicationServices.Services.ICategory
    {
        /// <summary>
        /// Constructor to initialize the data access layer, Context Instance [Category].
        /// </summary>
        /// <param name="repositoryContext">Data Access Context Instance</param>
        public Category(Interfaces.DataAccess.ICategory repositoryContext, Core.ProcessServicesApplication.IProcessServicesApplication processServicesApplication, Base.Application.Validators.Category validator)
            : base(repositoryContext, processServicesApplication, validator) { }
    }
}