//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class of the implementation of the services of the application for the Entity (City)</summary>
namespace SoftwareOne.BaseLine.ApplicationServices.Services
{
    /// <summary>
    /// Class of the implementation of the services of the application for the Entity (City)
    /// </summary>
    public partial class City :
        Core.Services.BaseApplicationServices<Entities.City,
                                              Interfaces.DataAccess.ICity,
                                              Base.Application.Validators.City>,
        Interfaces.ApplicationServices.Services.ICity
    {
        /// <summary>
        /// Constructor to initialize the data access layer, Context Instance [City].
        /// </summary>
        /// <param name="repositoryContext">Data Access Context Instance</param>
        public City(Interfaces.DataAccess.ICity repositoryContext, Core.ProcessServicesApplication.IProcessServicesApplication processServicesApplication, Base.Application.Validators.City validator)
            : base(repositoryContext, processServicesApplication, validator) { }
    }
}