//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class of the implementation of the services of the application for the Entity (Customer)</summary>
namespace SoftwareOne.BaseLine.ApplicationServices.Services
{
    /// <summary>
    /// Class of the implementation of the services of the application for the Entity (Customer)
    /// </summary>
    public partial class Customer :
        Core.Services.BaseApplicationServices<Entities.Customer,
                                              Interfaces.DataAccess.ICustomer,
                                              Base.Application.Validators.Customer>,
        Interfaces.ApplicationServices.Services.ICustomer
    {
        /// <summary>
        /// Constructor to initialize the data access layer, Context Instance [Customer].
        /// </summary>
        /// <param name="repositoryContext">Data Access Context Instance</param>
        public Customer(Interfaces.DataAccess.ICustomer repositoryContext, Core.ProcessServicesApplication.IProcessServicesApplication processServicesApplication, Base.Application.Validators.Customer validator)
            : base(repositoryContext, processServicesApplication, validator) { }
    }
}