//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class of the implementation of the services of the application for the Entity (Menu)</summary>
using SoftwareOne.BaseLine.Core.RequestDto;

namespace SoftwareOne.BaseLine.ApplicationServices.Services
{
    /// <summary>
    /// Class of the implementation of the services of the application for the Entity (Menu)
    /// </summary>
    public partial class Menu :
        Core.Services.BaseApplicationServices<Entities.Menu,
                                              Interfaces.DataAccess.IMenu,
                                              Base.Application.Validators.Menu>,
        Interfaces.ApplicationServices.Services.IMenu
    {
        /// <summary>
        /// Constructor to initialize the data access layer, Context Instance [Menu].
        /// </summary>
        /// <param name="repositoryContext">Data Access Context Instance</param>
        public Menu(Interfaces.DataAccess.IMenu repositoryContext, Core.ProcessServicesApplication.IProcessServicesApplication processServicesApplication, Base.Application.Validators.Menu validator)
            : base(repositoryContext, processServicesApplication, validator) { }

        public List<Entities.Menu> GetMenuByRole(int RoleId)
        {
            SwoParameterOfQuery<Entities.Menu> temp = new SwoParameterOfQuery<Entities.Menu>(x => x.Roles.Any(y => y.Id == RoleId));
            return _dataAccessEntity.ListAllAsync(temp).Result;
        }
    }
}