//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class of the implementation of the services of the application for the Entity (Role)</summary>
namespace SoftwareOne.BaseLine.ApplicationServices.Services
{
    /// <summary>
    /// Class of the implementation of the services of the application for the Entity (Role)
    /// </summary>
    public partial class Role :
        Core.Services.BaseApplicationServices<Entities.Role,
                                              Interfaces.DataAccess.IRole,
                                              Base.Application.Validators.Role>,
        Interfaces.ApplicationServices.Services.IRole
    {
        /// <summary>
        /// Constructor to initialize the data access layer, Context Instance [Role].
        /// </summary>
        /// <param name="repositoryContext">Data Access Context Instance</param>
        public Role(Interfaces.DataAccess.IRole repositoryContext, Core.ProcessServicesApplication.IProcessServicesApplication processServicesApplication, Base.Application.Validators.Role validator)
            : base(repositoryContext, processServicesApplication, validator) { }
    }
}