//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Class of the implementation of the services of the application for the Entity (ShippingAddress)</summary>
namespace SoftwareOne.BaseLine.ApplicationServices.Services
{
    /// <summary>
    /// Class of the implementation of the services of the application for the Entity (ShippingAddress)
    /// </summary>
    public partial class ShippingAddress :
        Core.Services.BaseApplicationServices<Entities.ShippingAddress,
                                              Interfaces.DataAccess.IShippingAddress,
                                              Base.Application.Validators.ShippingAddress>,
        Interfaces.ApplicationServices.Services.IShippingAddress
    {
        /// <summary>
        /// Constructor to initialize the data access layer, Context Instance [ShippingAddress].
        /// </summary>
        /// <param name="repositoryContext">Data Access Context Instance</param>
        public ShippingAddress(Interfaces.DataAccess.IShippingAddress repositoryContext, Core.ProcessServicesApplication.IProcessServicesApplication processServicesApplication, Base.Application.Validators.ShippingAddress validator)
            : base(repositoryContext, processServicesApplication, validator) { }
    }
}