//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareOne.BaseLine.ApplicationTexts {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceValidations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareOne.BaseLine.ApplicationTexts.ResourceValidations", typeof(ResourceValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied password is not valid for the user: {0}..
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User: {0}, is currently inactive to enter the application..
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User: {0}, does not exist in the system..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password hash size is invalid..
        /// </summary>
        public static string PasswordHashSizeInvalid {
            get {
                return ResourceManager.GetString("PasswordHashSizeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request data is not valid.
        /// </summary>
        public static string InvalidRequestData {
            get {
                return ResourceManager.GetString("InvalidRequestData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The field can't be null.
        /// </summary>
        public static string FieldCantBeNull {
            get {
                return ResourceManager.GetString("FieldCantBeNull", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Field Can't be empty.
        /// </summary>
        public static string FieldCantBeEmpty {
            get {
                return ResourceManager.GetString("FieldCantBeEmpty", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Invalid Length.
        /// </summary>
        public static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decimal.
        /// </summary>
        public static string InvalidDecimal {
            get {
                return ResourceManager.GetString("InvalidDecimal", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The token is required.
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string for CodeUniqueKey.
        /// </summary>
        public static string CodeUniqueKey {
            get {
                return ResourceManager.GetString("CodeUniqueKey", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string for CodeInsertValuessNull.
        /// </summary>
        public static string CodeInsertValuessNull {
            get {
                return ResourceManager.GetString("CodeInsertValuessNull", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string for CodeConflictRestriccion.
        /// </summary>
        public static string CodeConflictRestriccion {
            get {
                return ResourceManager.GetString("CodeConflictRestriccion", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string for CodeDataTruncated.
        /// </summary>
        public static string CodeDataTruncated {
            get {
                return ResourceManager.GetString("CodeDataTruncated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string for CodeViolationOfMaxValueConstraint.
        /// </summary>
        public static string CodeViolationOfMaxValueConstraint {
            get {
                return ResourceManager.GetString("CodeViolationOfMaxValueConstraint", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string for GeneralSqlException.
        /// </summary>
        public static string GeneralSqlException {
            get {
                return ResourceManager.GetString("GeneralSqlException", resourceCulture);
            }
        }

        
    }
}
