//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Interface that represents the Dao implementations for the entity (Audit)</summary>
namespace SoftwareOne.BaseLine.Interfaces.DataAccess
{
    /// <summary>
    /// Interface that represents the Dao implementations for the entity (Audit)
    /// </summary>
    public partial interface IAudit :
        Core.DataAccess.IBaseRepositoryDataAccess<Entities.Audit>
    { }
}