//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Interface represents the Implementations of the Dao for the Entity (Menu)</summary>
namespace SoftwareOne.BaseLine.Interfaces.DataAccess
{
    /// <summary>
    /// Interface represents the Implementations of the Dao for the Entity (Menu)
    /// </summary>
    public partial interface IMenu :
        Core.DataAccess.IBaseRepositoryDataAccess<Entities.Menu>
    { }
}