//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Jessica Antía Hortúa</author>
// <email>mailto:jessica.antia@softwareone.com</email>
// <summary>Test class to check the functionality of the entity [Role]</summary>
using SoftwareOne.BaseLine.Api.Controllers;
using SoftwareOne.BaseLine.Interfaces.ApplicationServices.Facade;
using Moq;
using SoftwareOne.BaseLine.Core.RequestDto;
using Microsoft.AspNetCore.Authorization;
using SoftwareOne.BaseLine.Core.ProcessServicesApplication;

namespace SoftwareOne.BaseLine.TestApplication
{
    public class RoleControllerTest
    {
        private readonly Mock<IAuthorizationService> authorizationService;

        private readonly Mock<Interfaces.DataAccess.IRole> repositoryContext;
        private readonly Mock<IProcessServicesApplication> processServicesApplication;

        public RoleControllerTest() {
            authorizationService = new Mock<IAuthorizationService>();
            repositoryContext = new Mock<Interfaces.DataAccess.IRole>();
            processServicesApplication = new Mock<IProcessServicesApplication>();
        }

        [Fact]
        public async Task Get_ValidRequest_ReturnsRoles()
        {
            Base.Application.Validators.Role validator = new Base.Application.Validators.Role();
            Interfaces.ApplicationServices.Services.IRole applicationServices = 
                new SoftwareOne.BaseLine.ApplicationServices.Services.Role(repositoryContext.Object, processServicesApplication.Object, validator);
            IRole facade = new SoftwareOne.BaseLine.ApplicationServices.Facade.Role(applicationServices);
            List<Entities.Role> resultList = new List<Entities.Role> {
                new Entities.Role{
                    Id = 1,
                    Name = "Role 1"
                }
            };
            repositoryContext.Setup(x => x.ListAllAsync(It.IsAny<SwoParameterOfQuery<Entities.Role>>())).Returns(Task.FromResult(resultList));
            // Arrange
            var service = new RoleController(facade, authorizationService.Object); 

            // Act
            var getResponse = await service.Get();

            // Assert
            Assert.NotNull(getResponse);
            Assert.Equal(1, getResponse.Count);
        }
    }
}