//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright company="SoftwareOne">Copyright(c) 2023 All Rights Reserved.</copyright>
// <author>Santiago Gil Roldán</author>
// <email>mailto:santiago.gil2@softwareone.com</email>
// <summary>Implementation class for the facade of the application services for the Entity (Category)</summary>
using AutoMapper;

namespace SoftwareOne.BaseLine.ApplicationServices.Facade
{
    /// <summary>
    /// Implementation class for the facade of the application services for the Entity (Category)
    /// </summary>
    public partial class Category :
        Core.Facade.BaseApplicationFacade<Entities.Category,
                                     EntitiesDto.Category,
                                     Interfaces.ApplicationServices.Services.ICategory>,
        Interfaces.ApplicationServices.Facade.ICategory
    {
        /// <summary>
        /// Constructor to initialize the application services layer, Context Instance [Category].
        /// </summary>
        /// <param name="applicationServices">Context instance for application services</param>
        public Category(Interfaces.ApplicationServices.Services.ICategory applicationServices) : base(applicationServices) {
            _mapper = new Mapper(configMapperFacade);
        }
    }
}